# This Dockerfile simply confirms that our script is sufficient in a
# BARE ubuntu environment.

FROM ubuntu:14.04
RUN apt-get update
RUN apt-get install -y curl

# When running the install script as root, I need the nixbld group to 
# pre-exist [2016.05.14]:
RUN addgroup nixbld
RUN useradd -c "Nix build user $n" \
      -d /var/empty -g nixbld -G nixbld -M -N -r -s "$(which nologin)" \
      nixbld01;
# This is also expected by the nix install script;
ENV USER root

# ------------------------------------------------------------
ADD . /scripts

# The script pauses to read from the user:
RUN echo yes | /scripts/multi_user_install.sh

RUN /nix/var/nix/profiles/default/bin/nix-env -q

ENV PATH $PATH:/nix/var/nix/profiles/default/bin/
ENV NIX_REMOTE daemon

CMD (nix-daemon &); bash

